name: Deploy on EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t mtug812/calculatorapp2:latest -f C:\Users\maria\Desktop\my-node-app\Dockerfile C:\Users\maria\Desktop\my-node-app

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker Push
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/calculatorapp2:latest"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: SSH Connection to EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2_IP }} << 'ENDSSH'
              sudo yum update -y
              sudo yum upgrade -y
              sudo yum install -y docker
              sudo systemctl enable docker.service
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo docker pull "${{ secrets.DOCKERHUB_USERNAME }}/calculatorapp2:latest"
          ENDSSH

      - name: Stop and Remove Existing Docker Containers
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2_IP }} << 'ENDSSH'
              docker stop calculatorapp2 || true
              docker rm calculatorapp2 || true
          ENDSSH

      - name: Start Docker Container on EC2 instance
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2_IP }} << 'ENDSSH'
              docker run -d -p 80:3000 --name calculatorapp2 "${{ secrets.DOCKERHUB_USERNAME }}/calculatorapp2:latest"
          ENDSSH

      - name: Clean Up SSH Key File (optional)
        run: |
          rm ~/.ssh/meinPrivateKey
